apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gvgyl6fq2-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/gvgyl6fq2-dotnet-basic-gitops